// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pharma.API.Data;

#nullable disable

namespace Pharma.API.Migrations
{
    [DbContext(typeof(PharmaContext))]
    [Migration("20220628193544_Migration_Orders")]
    partial class Migration_Orders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pharma.API.Model.AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.HasIndex("PersonId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.PersonModel", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.PharmaModel", b =>
                {
                    b.Property<int>("PharmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PharmaId"));

                    b.Property<string>("PharmaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PharmaId");

                    b.ToTable("Pharma", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.ProductModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitOfMeasurementId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.ProductTypeModel", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductTypeId");

                    b.ToTable("ProductType", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.StockItemModel", b =>
                {
                    b.Property<int>("StockItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockItemId"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<float>("UnitaryValue")
                        .HasColumnType("real");

                    b.HasKey("StockItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockId");

                    b.ToTable("StockItem", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.StockModel", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PharmaId")
                        .HasColumnType("integer");

                    b.HasKey("StockId");

                    b.HasIndex("PharmaId");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.StockTransactionItemModel", b =>
                {
                    b.Property<int>("StockTransactionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockTransactionItemId"));

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("StockItemId")
                        .HasColumnType("integer");

                    b.Property<int>("StockTransactionId")
                        .HasColumnType("integer");

                    b.Property<float>("UnitaryValue")
                        .HasColumnType("real");

                    b.HasKey("StockTransactionItemId");

                    b.HasIndex("StockItemId");

                    b.HasIndex("StockTransactionId");

                    b.ToTable("StockTransactionItem", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.StockTransactionModel", b =>
                {
                    b.Property<int>("StockTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockTransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("StockTransactionId");

                    b.HasIndex("TransactionStatusId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("StockTransaction", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.TransactionStatusModel", b =>
                {
                    b.Property<int>("TransactionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionStatusId");

                    b.ToTable("TransactionStatus", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.TransactionTypeModel", b =>
                {
                    b.Property<int>("TransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionTypeId");

                    b.ToTable("TransactionType", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.UnitOfMeasurementModel", b =>
                {
                    b.Property<int>("UnitOfMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitOfMeasurementId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UnitOfMeasurementId");

                    b.ToTable("UnitOfMeasurement", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("PharmaId")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PharmaId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.UserTypeModel", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType", (string)null);
                });

            modelBuilder.Entity("Pharma.API.Model.AddressModel", b =>
                {
                    b.HasOne("Pharma.API.Model.PersonModel", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Pharma.API.Model.ProductModel", b =>
                {
                    b.HasOne("Pharma.API.Model.ProductTypeModel", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharma.API.Model.UnitOfMeasurementModel", "UnitOfMeasurement")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("Pharma.API.Model.StockItemModel", b =>
                {
                    b.HasOne("Pharma.API.Model.ProductModel", "Product")
                        .WithMany("StockItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharma.API.Model.StockModel", "Stock")
                        .WithMany("StockItems")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Pharma.API.Model.StockModel", b =>
                {
                    b.HasOne("Pharma.API.Model.PharmaModel", "Pharma")
                        .WithMany("Stocks")
                        .HasForeignKey("PharmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharma");
                });

            modelBuilder.Entity("Pharma.API.Model.StockTransactionItemModel", b =>
                {
                    b.HasOne("Pharma.API.Model.StockItemModel", "StockItem")
                        .WithMany("StockTransactionItems")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pharma.API.Model.StockTransactionModel", "StockTransaction")
                        .WithMany("StockTransactionItems")
                        .HasForeignKey("StockTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");

                    b.Navigation("StockTransaction");
                });

            modelBuilder.Entity("Pharma.API.Model.StockTransactionModel", b =>
                {
                    b.HasOne("Pharma.API.Model.TransactionStatusModel", "TransactionStatus")
                        .WithMany("StockTransactions")
                        .HasForeignKey("TransactionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharma.API.Model.TransactionTypeModel", "TransactionType")
                        .WithMany("StockTransactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharma.API.Model.UserModel", "User")
                        .WithMany("StockTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionStatus");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pharma.API.Model.UserModel", b =>
                {
                    b.HasOne("Pharma.API.Model.PersonModel", "Person")
                        .WithMany("User")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharma.API.Model.PharmaModel", "Pharma")
                        .WithMany("Users")
                        .HasForeignKey("PharmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharma.API.Model.UserTypeModel", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Pharma");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Pharma.API.Model.PersonModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pharma.API.Model.PharmaModel", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pharma.API.Model.ProductModel", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("Pharma.API.Model.ProductTypeModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pharma.API.Model.StockItemModel", b =>
                {
                    b.Navigation("StockTransactionItems");
                });

            modelBuilder.Entity("Pharma.API.Model.StockModel", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("Pharma.API.Model.StockTransactionModel", b =>
                {
                    b.Navigation("StockTransactionItems");
                });

            modelBuilder.Entity("Pharma.API.Model.TransactionStatusModel", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Pharma.API.Model.TransactionTypeModel", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Pharma.API.Model.UnitOfMeasurementModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pharma.API.Model.UserModel", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Pharma.API.Model.UserTypeModel", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
